### ISSUE TITLE
Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included or the current platform. (Unity 2020.3.10f1 LTS)

### ISSUE THREAD

**Issue by lukeskt** [sketchfab/unity-plugin#9]
Hi there,

Sketchfab plugin has broken on 2020.3 LTS, I'm getting the following errors on importing the package:

![image](https://user-images.githubusercontent.com/18055384/122382297-af9cd380-cf61-11eb-9599-00dc895367f9.png)

Let me know if you need more info.

Thanks!

**Comment by PhiMue86** [comment]
Same for me. Renaming the file in the Sketchfab for Unity folder removes the error, but I haven't checked if everything still works.

**Comment by SabinT** [comment]
This error means that something else in the Unity project already has `Newtonsoft.Json` as a dependency, so now the project has 2 versions of the same library as 2 DLLs. Hence one of them needs to be removed. Most likely Unity themselves started using `Newtonsoft.Json` in one of the built-in packages at some point, which means the sketchfab package would import fine without errors in older versions of Unity, and would need to have this dependency in order to support older versions of Unity that don't include `Newtonsoft.Json` by default.

I think this might be solved by converting the sketchfab unitypackage into a UPM package, where dependencies can be specified via a `package.json`. IIRC, this file supports semver, so it should be possible for the sketchfab package to specify a version range that is compatible with the existing dependencies of Unity's built in packages.

**Comment by SabinT** [comment]
Well actually the problem is even worse in 2021. Even if you remove the sketchfab DLL, you still get an error, because sketchfab expects one version of Newtonsoft.Json, but Unity has another.

Error for reference (Unity 2021.1.13f1) - after deleting sketchfab's `Newtonsoft.Json.dll` and trying to reimport:
```
Assembly 'Assets/Sketchfab For Unity/Dependencies/Libraries/GLTFSerialization.dll' will not be loaded due to errors:
GLTFSerialization references strong named Newtonsoft.Json Assembly references: 10.0.0.0 Found in project: 12.0.0.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"
```

**Comment by SabinT** [comment]
Confirmed that in 2021 for this to work, you have to turn off strong name validation (after deleting Newtonsoft.dll), and reimport.
![image](https://user-images.githubusercontent.com/3022522/127286124-a35f6dd0-a679-42d0-af00-09a8f66d2b1f.png)

**Comment by AurL** [comment]
Hi
A new version with a fix for this `Newtonsoft.json` conflict has just been released: https://github.com/sketchfab/unity-plugin/releases/tag/1.2.1
The plugin should work with versions 2020+ now.

(Note that there are still other conflicts to handle , like the one on `Ionic.Zip` )

**Comment by lukeskt** [comment]
Thanks very much, can confirm this issue is resolved for me by the new release.

**Comment by NeonWizard** [comment]
> Hi A new version with a fix for this `Newtonsoft.json` conflict has just been released: https://github.com/sketchfab/unity-plugin/releases/tag/1.2.1 The plugin should work with versions 2020+ now.
> 
> (Note that there are still other conflicts to handle , like the one on `Ionic.Zip` )

I'm still having this issue with Unity 2019.4.31f and plugin version 1.2.1. Is there plans to fix this for Unity versions <2020?
